module.exports = {
  healthcheck: require('./healthcheck'),
  restaurants: require('./restaurants'),
  personnel: require('./personnel'),
  transactions: require('./transactions'),
  waiters: require('./waiters'),
  orders: require('./orders'),
  dishes: require('./dishes'),
  ingredients: require('./ingredients'),
  tables: require('./tables'),
  tokens: require('./tokens'),
  login: require('./login'),
  upload: require('./upload'),
  sse: require('./sse'),
};
